-- core
require "phil.plugins"
require "phil.options"
require "phil.theme"
require "phil.keymaps"
-- require "phil.statusline"
require "phil.lualine"
-- require "phil.heirline"

-- plugins
require "phil.nvim-cmp"
require "phil.lsp.null"
require "phil.lsp.lsp-installer"
require "phil.lsp.lspconfig"
require "phil.luasnip"
require "phil.lsp.keymaps"
require "phil.telescope"
-- require "phil.nvim-tree"
require "phil.neo-tree"
require "phil.treesitter"
require "phil.comment"
require "phil.surround"
require "phil.autopairs"
require "phil.bufferline"
require "phil.gitsigns"
require "phil.toggleterm"
require "phil.whichkey"
require "phil.outline"
require "phil.markdown-preview"
-- require "phil.neorg"
