-- local actions = require("telescope.actions")
-- local trouble = require("trouble.providers.telescope")
-- require("trouble.sources.telescope").open()
--
-- local telescope = require("telescope")
--
-- telescope.setup({
-- 	defaults = {
-- 		mappings = {
-- 			i = { ["<c-t>"] = require("trouble.sources.telescope").open() },
-- 			n = { ["<c-t>"] = require("trouble.sources.telescope").open() },
-- 		},
-- 	},
-- })
--
