return {
	"catppuccin/nvim",
	name = "catppuccin",
	priority = 1000,
	config = function()
		vim.opt.termguicolors = true

		require("catppuccin").setup({
			flavor = "mocha",
			background = { light = "latte", dark = "mocha" },
			transparent_background = false,
			show_end_of_buffer = false,
			term_colors = true,
			dim_inactive = { enabled = false },
			time_traveller = { enabled = false },
			integrations = {
				cmp = true,
				gitsigns = true,
				heirline = true,
				neo_tree = true,
				nvim_tree = true,
				treesitter = true,
				telescope = true,
				mason = true,
				markdown = true,
				which_key = true,
				lsp_trouble = true,
				native_lsp = { enabled = true },
			},
			custom_highlights = function(colors)
				return {
					CmpItemMenu = { fg = colors.subtext0 },
					CmpItemAbbrDeprecated = { fg = colors.subtext1, strikethrough = true },
					CmpItemAbbrMatch = { fg = colors.blue, bold = true },
					CmpItemAbbrMatchFuzzy = { fg = colors.blue, bold = true },
					CmpItemKindDefault = { fg = colors.blue },
					CmpItemMenu = { fg = colors.subtext0 },
					CmpItemAbbrDeprecated = { fg = colors.subtext1, strikethrough = true },
					CmpItemAbbrMatch = { fg = colors.blue, bold = true },
					CmpItemAbbrMatchFuzzy = { fg = colors.blue, bold = true },
					CmpItemKindDefault = { fg = colors.blue },
					CursorLineNumber = { fg = colors.text },
					NormalFloat = { bg = "none" },
					FloatBorder = { bg = "none" },
					TelescopeNormal = { bg = "none" },
					TelescopeBorder = { bg = "none" },
					TelescopePreviewTitle = { fg = colors.blue, bold = true },
					TelescopeResultsTitle = { fg = colors.blue, bold = true },
					TelescopeSelectionCaret = { fg = colors.blue },
					TelescopeSelection = { bg = colors.surface0 },
					NormalFloat = { bg = "none" },
					FloatBorder = { bg = "none" },
					TelescopeNormal = { bg = "none" },
					TelescopeBorder = { bg = "none" },
					TelescopePreviewTitle = { fg = colors.blue, bold = true },
					TelescopeResultsTitle = { fg = colors.blue, bold = true },
					TelescopeSelectionCaret = { fg = colors.blue },
					TelescopeSelection = { bg = colors.surface0 },
					NeoTreeNormal = { bg = "none" },
					NeoTreeNormalNC = { bg = "none" },
					NeoTreeFloatBorder = { bg = "none" },
					NeoTreeFloatTitle = { fg = colors.blue, bold = true },
					WinSeparator = { bg = "none", fg = colors.surface2 },
					SignColumn = { bg = "none" },
					LineNr = { fg = colors.subtext0 },
					CursorLineNr = { fg = colors.text, bold = true },
					NeoTreeGitModified = { fg = colors.peach },
					NeoTreeGitAdded = { fg = colors.green },
					NeoTreeGitDeleted = { fg = colors.red },
					NeoTreeGitUntracked = { fg = colors.blue },
					NeoTreeGitIgnored = { fg = colors.subtext0 },
					NeoTreeGitStaged = { fg = colors.yellow },
					NeoTreeGitMerge = { fg = colors.magenta },
					NeoTreeGitConflict = { fg = colors.maroon },
					NeoTreeGitRenamed = { fg = colors.teal },
					NeoTreeGitUnmerged = { fg = colors.pink },
					NeoTreeGitStaged = { fg = colors.yellow },
					NeoTreeGitMerge = { fg = colors.magenta },
					NeoTreeGitConflict = { fg = colors.maroon },
					NeoTreeGitRenamed = { fg = colors.teal },
					NeoTreeGitUnmerged = { fg = colors.pink },
					LspReferenceText = { bg = colors.surface0 },
					LspReferenceRead = { bg = colors.surface0 },
					LspReferenceWrite = { bg = colors.surface0 },
					LspInlayHint = { fg = colors.subtext0, bg = "none" },
					LspCodeLens = { fg = colors.subtext0, bg = "none" },
					NormalFloat = { bg = "none" },
					FloatBorder = { bg = "none" },
					TelescopeNormal = { bg = "none" },
					TelescopeBorder = { bg = "none" },
					TelescopePreviewTitle = { fg = colors.blue, bold = true },
					TelescopeResultsTitle = { fg = colors.blue, bold = true },
					TelescopeSelectionCaret = { fg = colors.blue },
					TelescopeSelection = { bg = colors.surface0 },
				}
			end,
		})

		vim.cmd.colorscheme("catppuccin")

		vim.api.nvim_create_autocmd("ColorScheme", {
			pattern = "catppuccin",
			callback = function()
				vim.diagnostic.config({
					virtual_text = false,
					underlines = true,
					signs = true,
					update_in_insert = false,
					severity_sort = true,
					underline = true,
				})
			end,
		})
	end,
}
